"""
Share Key model and schemas.
Stores encrypted time-limited access keys that patients generate for doctors.
"""

import uuid
from datetime import datetime
from typing import Optional, Any

from sqlalchemy import Column, String, Integer, Boolean, DateTime, ForeignKey
from pydantic import BaseModel

from app.database import Base


class ShareKey(Base):
    """The 'share_keys' table. Each row = one access key generated by a patient."""
    __tablename__ = "share_keys"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    patient_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    # The actual key (stored as a hash — the plaintext is only shown once to the patient)
    share_key = Column(String, unique=True, nullable=False)  # In dev: store plaintext for simplicity
    passcode_hash = Column(String, nullable=False)           # SHA-256 hash of the 4-6 digit passcode

    # Access control
    permissions = Column(String, nullable=False, default="full")  # "full", "labs_only"
    expires_at = Column(DateTime, nullable=False)
    max_uses = Column(Integer, nullable=False, default=5)
    usage_count = Column(Integer, nullable=False, default=0)
    is_revoked = Column(Boolean, nullable=False, default=False)

    # Doctor info (optional, for the patient to track who they shared with)
    doctor_name = Column(String, nullable=True)
    doctor_specialty = Column(String, nullable=True)
    label = Column(String, nullable=True)  # e.g., "Dr. Patel — Cardiology checkup"

    created_at = Column(DateTime, default=datetime.utcnow)


# ─── Pydantic Schemas ───

class ShareKeyCreate(BaseModel):
    """Schema for generating a new share-key."""
    patient_id: str
    passcode: str                            # 4-6 digit PIN (e.g., "1234")
    permissions: str = "full"                # "full", "labs_only"
    expires_in_hours: int = 24               # How many hours until the key expires
    max_uses: int = 5                        # Max number of times the key can be used
    doctor_name: Optional[str] = None        # Optional: who is this key for?
    doctor_specialty: Optional[str] = None
    label: Optional[str] = None              # Optional: friendly label


class ShareKeyValidate(BaseModel):
    """Schema for validating a share-key (what the doctor sends)."""
    passcode: str  # The doctor enters the passcode given by the patient


class ShareKeyResponse(BaseModel):
    """Schema for returning share-key info to the PATIENT (not the doctor)."""
    id: str
    patient_id: str
    share_key: str          # The actual key (show to patient so they can share it)
    permissions: str
    expires_at: datetime
    max_uses: int
    usage_count: int
    is_revoked: bool
    doctor_name: Optional[str] = None
    doctor_specialty: Optional[str] = None
    label: Optional[str] = None
    created_at: datetime

    class Config:
        from_attributes = True


class DoctorAccessResponse(BaseModel):
    """Schema for data returned to the DOCTOR after successful validation."""
    patient_profile: Any       # Patient profile dict
    lab_reports: list          # List of lab reports
    trauma_pins: list          # List of trauma pins
    permissions: str           # What level of access was granted
    key_expires_at: datetime   # When this key expires
    usage_remaining: int       # How many more uses
